name: Build

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  NAMESPACE: ${{ github.repository_owner }}
  REMOTE_CACHE: "true"

jobs:
  detect-build-targets:
    runs-on: ubuntu-latest
      
    outputs:
      vtk-target-matrix: ${{ steps.generate.outputs.VTK_TARGET_MATRIX }}
      ttk-target-matrix: ${{ steps.generate.outputs.TTK_TARGET_MATRIX }}
      vtk-python-target-matrix: ${{ steps.generate.outputs.VTK_PYTHON_TARGET_MATRIX }}
      ttk-python-target-matrix: ${{ steps.generate.outputs.TTK_PYTHON_TARGET_MATRIX }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - id: generate
        run: |
          echo "::debug::$(docker buildx bake --print)" 

          echo "VTK_TARGET_MATRIX="$(docker buildx bake vtk --print | node scripts/detect-build-targets.js) >> "$GITHUB_OUTPUT"
          
          echo "TTK_TARGET_MATRIX="$(docker buildx bake ttk --print | node scripts/detect-build-targets.js) >> "$GITHUB_OUTPUT"

          echo "VTK_PYTHON_TARGET_MATRIX="$(docker buildx bake vtk-python --print | node scripts/detect-build-targets.js) >> "$GITHUB_OUTPUT"

          echo "TTK_PYTHON_TARGET_MATRIX="$(docker buildx bake ttk-python --print | node scripts/detect-build-targets.js) >> "$GITHUB_OUTPUT"

  vtk-build:
    needs: detect-build-targets
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    strategy:
      fail-fast: false
      matrix: 
        target: ${{ fromJson(needs.detect-build-targets.outputs.vtk-target-matrix) }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/bake-action@v3.1.0
        with:
          targets: ${{ matrix.target }}
          push: true

  ttk-build:
    needs: [detect-build-targets, vtk-build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    strategy:
      fail-fast: false
      matrix: 
        target: ${{ fromJson(needs.detect-build-targets.outputs.ttk-target-matrix) }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/bake-action@v3.1.0
        with:
          targets: ${{ matrix.target }}
          push: true

  vtk-python-build:
    needs: detect-build-targets
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    strategy:
      fail-fast: false
      matrix: 
        target: ${{ fromJson(needs.detect-build-targets.outputs.vtk-python-target-matrix) }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/bake-action@v3.1.0
        with:
          targets: ${{ matrix.target }}
          push: true

  ttk-python-build:
    needs: [detect-build-targets, vtk-python-build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    strategy:
      fail-fast: false
      matrix: 
        target: ${{ fromJson(needs.detect-build-targets.outputs.ttk-python-target-matrix) }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/bake-action@v3.1.0
        with:
          targets: ${{ matrix.target }}
          push: true

  