name: Build

on:
  push:
    branches: ["main"]

jobs:
  detect-build-targets:
    runs-on: ubuntu-latest
      
    outputs:
      target-matrix: ${{ steps.generate.outputs.target-matrix }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - id: generate
        run: |
          echo "::debug::$(docker buildx bake --print)" 
          TARGET_MATRIX=$(docker buildx bake --print | node scripts/detect-build-targets.js)
          echo "::debug::$TARGET_MATRIX"
          echo "::set-output name=target-matrix::$TARGET_MATRIX"
        env:
          NUMBER_OF_JOBS: 2

  build:
    needs: detect-build-targets
    runs-on: ubuntu-latest

    strategy:
      matrix: 
        target: ${{ fromJson(needs.detect-build-targets.outputs.target-matrix) }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/bake-action@v3.1.0
        with:
          targets: ${{ matrix.target }}
          push: false